export const actions = {
    post : {
      POST_FETCHING:'POST_FETCHING',
      POST_FETCHED:'POST_FETCHED',
      POST_EDIT:'POST_EDIT',
      POST_DELETE:'POST_DELETE',
      POST_ERROR:'POST_ERROR',
    },
    profile:{
      PROFILE_FETCHING:'PROFILE_FETCHING',
      PROFILE_FETCHED:'PROFILE_FETCHED',
      PROFILE_EDIT:'PROFILE_EDIT',
      PROFILE_IMAGE_UPLOAD:'PROFILE_IMAGE_UPLOAD',
      PROFILE_ERROR:'PROFILE_ERROR'
    }
}